FROM hexpm/elixir:1.13.4-erlang-25.0.1-ubuntu-focal-20211006

RUN mix local.hex --force && mix local.rebar --force

WORKDIR /var/app

COPY mix.exs /var/app/mix.exs
COPY mix.lock /var/app/mix.lock

RUN mix do deps.get --only $MIX_ENV, deps.compile, compile
